name: Sync main with develop branch
on:
  workflow_run:
    workflows: [Deploy to Prod (Post Merge)]
    types:
      - completed
    

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge develop -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: develop
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}